version: '3.8'

services:
  jotihunt-forwarder:
    image: ghcr.io/ScoutingScherpenzeel/jotihunt-forwarder:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables from a .env file
    volumes:
      - ./session:/app/session  # Mount a volume for session persistence
    restart: unless-stopped  # Automatically restart the bot unless it is stopped manually